kubernetes-sigs/hydrophone

- main.go
- pkg/client/check.go
- pkg/client/client.go
- pkg/client/pod_log.go
- pkg/service/args.go
- pkg/service/const.go
- pkg/service/init.go
Why we need this PR -
- This PR contains code that will take advantage of the `--focus` option that will let people run a specific e2e test.
`./bin/k8s-run-e2e --focus sig-auth`
- This PR has the code that will create exactly the same objects mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/test/conformance/image/conformance-e2e.yaml)
- This PR also has the code that will clean up the objects after getting all the logs.
> Add focus option & Use go code to create conformance objects

- main.go
- pkg/client/check.go
- pkg/client/pod_log.go
- pkg/service/args.go
What is this PR for -
- Add functions for creating directory and file(pod name).
- Add code that will write the logs in the file.
Other Minor changes -
- Call the `Cleanup` function so that after done with logs it will clear the resources.
Test -
```bash
./bin/k8s-run-e2e --focus sig-auth --output conformance_log
```
> Add `--output` option to store logs in a file specified

- main.go
- pkg/service/args.go
- pkg/service/init.go
What is this PR for -
- Add the `--image` option to choose a custom conformance container image.
Other Minor changes -
- Add a check to see if the object already exists or not and ignore them while creating.
Test -
```bash
./bin/k8s-run-e2e --focus sig-auth --image registry.k8s.io/conformance-amd64:v1.24.0
```
> Add `--image` option for custom conformance container image

- main.go
- pkg/service/args.go
- pkg/service/init.go
- pkg/service/init_test.go
This PR adds a `--kubeconfig` option that will override the `$KUBECONFIG` or `~/.kube/config` defaults.
> Added --kubeconfig flag

- README.md
- pkg/service/args.go
This PR updates the readme to address using the kubeconfig option as an alternate to the defaults.
> updated readme with `--kubeconfig` option

- .github/workflows/test.yml
I don't like how the action is currently running three times per PR (twice on pull request, once on push to main) https://github.com/dims/hydrophone/actions
This PR will make the action only run on Push whether it's during a PR or post PR to main.  
ref: https://github.com/dims/hydrophone/issues/16
> Fix actions duplicate run

- .github/workflows/periodic_e2e.yml
This PR adds a github actions workflow to run the full conformance test every three hours. 
ref: https://github.com/dims/hydrophone/issues/16
> Added periodic full conformance tests

- main.go
- pkg/client/check.go
- pkg/client/client.go
This PR makes the exit code of the program the same as the exit code of the conformance pod. 
ref: https://github.com/dims/hydrophone/issues/16
> Tie program exit code to pod exit code

- .github/workflows/test.yml
This PR adds a linting stage to the CI. We need both lines to 1. show the output if any files are not properly formatted and 2. evaluate if there is any output of gofmt. If there is no output the stage succeeds, if there is an output then the stage fill fail. 
Example of failing stage: https://github.com/rjsadow/hydrophone/actions/runs/7300833583/job/19896266284#step:4:1
> Adding gofmt stage to CI

- README.md
- pkg/common/args.go
- pkg/service/init.go
Added `--dry-run` to more quickly test without needing for the conformance tests to run. 
Example output:
```
→ bin/hydrophone --conformance --dry-run
2023/12/23 06:02:35 API endpoint : https://127.0.0.1:37235
2023/12/23 06:02:35 Server version : version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.0", GitCommit:"3f7a50f38688eb332e2a1b013678c6435d539ae6", GitTreeState:"clean", BuildDate:"2023-12-14T19:18:17Z", GoVersion:"go1.21.5", Compiler:"gc", Platform:"linux/amd64"}
2023/12/23 06:02:35 Running tests : '\[Conformance\]'
2023/12/23 06:02:35 Using conformance image : 'registry.k8s.io/conformance:v1.29.0'
2023/12/23 06:02:35 Using busybox image : 'registry.k8s.io/e2e-test-images/busybox:1.36.1-1'
2023/12/23 06:02:35 Test framework will start '1' threads and use verbosity '4'
2023/12/23 …
```
> Add dry run mode option

- hack/bump-k8s.sh
Update how `HYDROPHONE_ROOT` is determined. This way if the script ever moves for some reason, the root path isn't relative to the script.
> Change how root dir is found in `bump-k8s.sh`

- pkg/service/init.go
This PR fixes when the `E2E_DRYRUN` variable is included in the pod spec. The conformance image checks for if the variable exists at all vs what it's set to for enabling dryrun support (https://github.com/kubernetes/kubernetes/blob/master/test/conformance/image/go-runner/cmd.go#L72-L74). Previously dryrun was included on all executions. This will fix that to only include the variable if the `--dry-run` flag is set.
> Fix DryRun flag inclusion

- README.md
Thanks so much for the great work @aniruddha2000 @dims :pray: :heart: 
Ran through the examples listed in the README. Everything ran smoothly so far.
Just hit a minor flag typo error in the following example. PR fixes that. :slightly_smiling_face: 
```
psaggu@omega:~/test-hydrophone/hydrophone$ bin/hydrophone --image 'registry.k8s.io/conformance:v1.29.0'
flag provided but not defined: -image
Usage of bin/hydrophone:
-busybox-image string
specify an alternate busybox container image. (default "registry.k8s.io/e2e-test-images/busybox:1.36.1-1")
-cleanup
cleanup resources (pods, namespaces etc).
-conformance
run conformance tests.
-conformance-image string
specify a conformance container image of your choice. (default "registry.k8s.io/conformance:v1.29.0")
-dry-run
run in dry run mode. …
```
> minor typo fix - correct conformance-image flag in example test run

- .github/workflows/test.yml
This PR adds some workflow tests to to ensure that the dry-run flag works as expected.
The tests look for the execution time of gingko and evaluate the time that gingko ran. In dry-run mode no pods or tests should execute so there's an expected duration threshold set to 5 seconds. 5 seconds was chosen because realistically, dryrun executions be significantly less than this (0-2 seconds) and if a non-dryrun test is ran then we should expect 20-30 seconds minimum. 
Note, this PRs workflows will continue to fail until https://github.com/dims/hydrophone/pull/56 is merged with it.
> Added tests for dryrun

- .github/workflows/test.yml
The previous test was using the wrong log to calculate the non dry run duration.
> Fix dryrun test

- .github/workflows/periodic_conformance.yml
- .github/workflows/periodic_e2e.yml
- .github/workflows/test.yml
tip from way back :)
https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-529154066
> Run etcd using tmpfs storage

- main.go
- pkg/client/check.go
fix: #59 
This PR moves the determination of the exit code to after the main loop runs and log files are exported.
> Fix order of pod termination and log download

- hack/dryrun-e2e.sh
Adds a dryrun test to help me figure out the test-infra config that will be used. It's very likely that this script will be replaced with either a common script or some other update in k/k to use hydrophone.
> Added dry-run test

- hack/dryrun-e2e.sh
Sets a different results directory for the dryrun test. 
Regroups some logic for checking the duration.
> Minor fixes to dryrun-e2e.sh

- hack/run-e2e.sh
Prioritize conformance over focus and skip when determining flags.
> Changed run-e2e to manage --conformance

- hack/run-e2e.sh
This should help resolve an issue where focus is being passed without a focus set. 
ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/hydrophone-e2e-check/1747986869506805760#1:build-log.txt%3A110-138
> Updated e2e script to better handle focus and skip

- main.go
- pkg/service/list_images.go
> Removed unwanted arguments and parametres

- hack/run-e2e.sh
This change adds a check for the number of tests that are expected to run during any given job. For example, several times while updating the script I would make a change and instead of 1 spec running, there would be 19 specs ran. With this validation we'll be able to explicitly expect a certain number of tests to run.
> Adding evaluation for number of tests

- pkg/client/check.go
Fix https://github.com/kubernetes-sigs/hydrophone/issues/123
> Remove redundant error check in  client.PrintE2ELogs()

- cmd/root.go
Fixes a typo and adds copyright in `cmd/root.go`
> fix: typo and copyright

- pkg/service/init.go
When k8s resource like Namespace, clusterrole, clusterrole, binding, service account  already exists in the cluster the RunE2E() test fails because the Create() operation returns error. But the error in the logs are not clear. Throw Fatal error when resource already exists and ask to run cleanup
Eg: when namespace already exists in the cluster I am getting below error 
```
reeta@Reetas-MacBook-Pro hydrophone % make run
go run main.go
12:20:53 INF API endpoint : https://127.0.0.1:57154
12:20:53 INF Server version : version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:42:59Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
12:20:53 INF Using conformance image : …
```
> Throw fatal error and ask user to run cleanup when a k8s resource already exists in the cluster

- cmd/root.go
- pkg/common/args.go
- pkg/common/args_test.go
- pkg/service/init.go
Fixes https://github.com/kubernetes-sigs/hydrophone/issues/95
verified run by passing additional flags
```
reeta@Reetas-MacBook-Pro hydrophone % go run main.go --extra-args="--list-conformance-tests=true,--allowed-not-ready-nodes=2"
23:12:36 INF API endpoint : https://127.0.0.1:50108
23:12:36 INF Server version : version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:42:59Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
23:12:36 INF Using conformance image : 'registry.k8s.io/conformance:v1.24.0'
23:12:36 INF Using busybox image : 'registry.k8s.io/e2e-test-images/busybox:1.36.1-1'
23:12:36 INF Test framework will start '1' threads and use verbosity '4'
23:12:36 INF …
```
> Add support for Additional Conformance Test Flags

- cmd/root.go
- pkg/common/args.go
- pkg/common/args_test.go
ValidateArgs(clientSet *kubernetes.Clientset, config *rest.Config) is not using the 2 params. Remove them and fix the unit test
> chore: Remove unneeded params passed to common.ValidateArgs function

- README.md
- cmd/root.go
- pkg/client/check.go
- pkg/client/client.go
- pkg/client/download.go
- pkg/client/pod_log.go
- pkg/common/args.go
- pkg/common/const.go
- pkg/service/init.go
add a new `--namespace` flag to set a custom namespace - no impact for existing users, because we keep the same default value
> feat: allow to customize the namespace

- cmd/root.go
- go.mod
- pkg/common/args.go
- pkg/common/args_test.go
Adds additional test cases for `args.go` in `args_test.go`.
> test: add tests for args.go

- pkg/service/init.go
During conformance testing nodes might get various tains set, to ensure the test pod survives all possibilities we're setting appropriate toleration which will match all possible taints.
/assign @rjsadow
> Set an empty key tolerations to match all tains on node

- hack/run-e2e.sh
- pkg/common/args.go
- pkg/common/args_test.go
The trimmedVersion function was removing the v prefix from the version tag but not adding it back, causing conformance image pulls to fail. 
Additionally, this PR adds an extra flag to the test script so that by default we will test out the trimmed version functions by not explicitly setting them.
> Prepend v to trimmedVersion

- cmd/root.go
- pkg/common/args.go
- pkg/common/args_test.go
- pkg/log/logs.go
- introduce common.SetDefaults to set defaults which are common for "conformance", "focus", "cleanup", "list-images" options
- rename ValidateArgs() -> ValidateConformanceArgs() as this is more specific to conformance image flags
- move spinner call to root.go
> refactor: have a common method for setting defaults and move spinner call to root.go

- pkg/service/init.go
fixes #161 
In previous when clusterrole and clusterrolebinding were present then both were logged exists one and created one both.
Previous action-
Current action-
> Improved logging for clusterrole and clusterbinding

- cmd/root.go
- pkg/client/check.go
- pkg/client/client.go
- pkg/client/download.go
- pkg/client/pod_log.go
- pkg/service/init.go
- pkg/service/list_images.go
This removes the TODO/Background contexts sprinkled throughout pkg/ and replaces them with a common context.Context parameter. The root command then uses the command's context for all the functions it calls.
> add context handling

- cmd/root.go
- pkg/client/client.go
Viper's computed file path `~/.config/hydrophone.yaml` on my system, and after running hydrophone, I do not have a `~/.config/hydrophone/` directory, so I presume the default values was simply a typo. The comment in line 155 agrees with me.
> fix help text for --config flag

- pkg/common/args.go
This removes what I think is a leftover from the original spinner implementation. Or does the delay have a specific reason, like to prewarm some cache?
> remove 2s delay on startup

- hack/boilerplate/boilerplate.py
- pkg/common/spinner.go
The current `boilerplate.py` script doesn't return an exit code to signal that the check failed, so the `make verify` command doesn't fail. It prints that files are missing boilerplate, but that is hidden in the prow job logs. The `verify` prow job succeeds though.
This PR updates the Python script to return exit code feedback so that `make verify` fails. I discovered a non-compliant file, `pkg/common/spinner.go`, which was contributed in #148 by @Bharadwajshivam28. I'm not 100% sure if this PR needs sign off by them (I assume the contribution is made under Apache license anyway).
> fail boilerplate check if non-compliant files are detected

- pkg/client/client.go
This code was missing O_TRUNC.
Without it, my first hydrophone run randomly had issues and was dumping a 142MB junit_01.xml, containing lots of pod logs. I then re-ran hydrophone on another cluster where the tests succeeded, but I still _seemingly_ got a 142MB file.
In reality, hydrophone was fetching a 2.5MB file and was only updating/replacing the first 2.5MB of my junit_01.xml file, instead of overwriting it completely.
Adding O_TRUNC would make this more or less equivalent to OpenFile(), except that Create() sets file permissions to 0666 instead of our 0600, which I think is perfectly acceptable. The junit/e2e logs are not secret data that should be kept from other users on the system.
> prevent broken junit report files

- .golangci.yml
- cmd/root.go
- hack/verify-golint.sh
- pkg/client/client.go
- pkg/common/args.go
- pkg/service/init.go
- pkg/service/init_test.go
- pkg/service/list_images.go
`golangci-lint` is a pretty good linter for Go projects. This updates the existing `hack/verify-golint.sh` script to install that instead of `golang.org/x/lint/golint`.
The `.golangci.yml` configuration file is adapted from https://github.com/kubernetes-sigs/krew/blob/master/.golangci.yml. Felt like a pretty good starting point, we can gradually enable linters that seem useful.
This PR is currently a WIP because the new linter uncovers a couple of problems, but some of them are already addressed in #165. I'll wait for that PR to move forward (in any direction) before fixing linter-discovered problems in this PR to minimise conflict with the existing PR.
> use golangci-lint as linter

- hack/run-e2e.sh
- pkg/client/download.go
- pkg/service/init.go
This PR makes it possible to run hydrophone concurrently in the same cluster by appending its namespace to the cluster-wide resource names (e.g. the ClusterRole `hydrophone` becomes `hydrophone:<namespace>`). I also fixed some leftover hardcoded names and changed the cleanup logic to just delete the namespace, letting Kubernetes take care of garbage collection.
> append namespace to resources to allow parallel conformance tests

- cmd/root.go
- docs/air-gapped.md
- hack/run-e2e.sh
- hack/verify-all.sh
- pkg/service/init.go
This PR makes more use of the `--verbosity` flag.
* The default value, 4, is kept with the same behaviour: Show a spinner.
* If v <= 2, then no spinner is shown, useful for e2e jobs.
* If v >= 6, then the spinner is replaced with the live test output.
This would fix #168.
> hide spinner on -v <= 2, show test logs in realtime with -v >= 6

- pkg/client/check.go
- pkg/common/pod.go
- pkg/service/list_images.go
I'm tring the hydrophone with my kind kubernetes `ghcr.io/liangyuanpeng/kindest/testnode:v1.31.0-alpha.0-24-g9791f0d1f39` and  since have not image `registry.k8s.io/conformance:v1.31.0`, hydrophone will never not exit until the github action 6-hour timeout limit is reached. ( I'm running it on the gthub action. )
So this PR is working for print the error message of ImagePullBackOff and let hydrophone  exit if conformance pod pending with ImagePullBackOff.
here is the logs after this PR.
```shell
$:~/lan/hydrophone$ bin/hydrophone --list-images 
23:17:14 INF API endpoint: https://127.0.0.1:38453/
23:17:14 INF Server version: version.Info{Major:"1", Minor:"31+", GitVersion:"v1.31.0-alpha.0.24+9791f0d1f39f3f", GitCommit:"9791f0d1f39f3f1e0796add7833c1059325d5098", GitTreeState:"clean", …
```
> Exit process if conformance pod ImagePullBackOff.

- cmd/root.go
This is the promised follow up to #170, removing the temporary `nolint` directive that I put there to make sure we didn't create any merge conflicts. Since the relevant PRs touching `cmd/root.go` are now merged, this should be safe again.
To avoid writing `if err := ...; err != nil { log.Fatal(err) }` ten times, I've added a little wrapper. I can undo that and go with the `if` pattern if that's preferred.
> Handle errors coming from `viper.BindPFlag`

- hack/run-e2e.sh
This PR bumps kind to the latest stable version and sets the kube version to kind's default node version.
I saw that https://github.com/kubernetes-sigs/hydrophone/actions/workflows/update-deps.yml is broken, @embik wanted to maybe take a look at it. That job can then bump us to 1.30, as intended.
> update kind in e2e tests to 0.22

- .github/workflows/update-deps.yml
It seems that the `update-deps` workflow is broken since #145, since that bumped the Go version in `go.mod` to 1.22. This should fix the workflow to get automated dependency updates again.
> Update update-deps workflow to Go 1.22

- hack/verify-golint.sh
There's really no good need to spend all that time compiling golangci-lint everytime a commit is tested.
This saves roughly a minute in CI.
> download a precompiled golangci-lint to save CI time

- DEVELOPMENT.md
- cmd/root.go
If the cluster is too weak or the network too flaky, it can happen that hydrophone loses connection to the test Pod. This currently means the test is basically dead and you have to start over.
This PR adds a new `--continue` flag which will simply skil the Pod creation and then connect to the existing Pod, effectively resuming the test and allowing the user to recover.
> add --continue flag to resume/reconnect to a running conformance test

- pkg/conformance/client/logs.go
Without this fix, if the test runs within the same process (when using as a library), the informer will keep running forever after the test execution.
> Stop informers on context cancelation

- main.go
- pkg/log/logs.go
If hydrophone is used as a library, setting a default logger in `init()` function might be not the best option.
> Set the default logger only in the CLI.

- pkg/conformance/cleanup.go
Without this fix, an attempt to run the test two times might fail, as the namespace hasn't been deleted yet.
> Wait for the namespace to be deleted.

- cmd/root.go
- pkg/conformance/deploy.go
> Add skip preflight check flag

- pkg/conformance/runner_test.go
**This PR includes the following changes:**
- Added unit tests for TestRunner.namespacedName in runner.go to improve code coverage.
- Capitalized Namespace in an error message: this aligns with Kubernetes' convention for built-in resource names and matches the pattern used elsewhere in the file.
**Notes**
-  No user-facing changes
-  Test-only and formatting update
PS: my first open source contribution 😃
> add unit test for namespacedName function

- .github/workflows/update-deps.yml
This bumps the go configured for the `update-deps` workflow to match the one configured in `go.mod`
resolves #244
> bumps update-deps go to match go.mod

- pkg/log/logs.go
Addresses the issue: https://github.com/kubernetes-sigs/hydrophone/issues/117
hydrophone logger now set to log time in UTC which aligns with the time logged by gingko run.
> set time to UTC

- .github/workflows/weekly-trivy-scan.yml
- Dockerfile
**What this PR does / why we need it:** Adds a new GitHub workflow for weekly vulnerability scanning of Hydrophone image. This helps us proactively identify security vulnerabilities before they become critical issues.
Test run: https://github.com/farazkhawaja/hydrophone/actions/runs/14956212113
> Add weekly vulnerability scans

- pkg/conformance/deploy.go
Addresses review comment: https://github.com/kubernetes-sigs/hydrophone/pull/232#discussion_r2087112560
Fixed error messages to follow Go best practices by starting with lowercase letters 
ref: https://go.dev/wiki/CodeReviewComments#error-strings
> fix err msgs

- cmd/root.go
- pkg/conformance/client/client.go
- pkg/conformance/client/logs.go
- pkg/conformance/client/logs_test.go
- pkg/types/config.go
- pkg/types/flags.go
Implements progress tracking by calculating percentage based on processed vs total test count to output logs during test execution
Periodically reads e2e.log from conformance pod via k8s exec API every 30 seconds
Original inspiration from @rjsadow work on progress indicator -- https://github.com/kubernetes-sigs/hydrophone/pull/225
Resolves #223 
```
14:39:35 INF API endpoint: https://127.0.0.1:6443
14:39:35 INF Server version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.5+k3s1", GitCommit:"56ec5dd4d012c1d77dc7f50f21f65183044c92e7", GitTreeState:"clean", BuildDate:"2025-01-28T17:45:21Z", GoVersion:"go1.22.10", Compiler:"gc", Platform:"linux/amd64"}
14:39:35 INF Using namespace: conformance
14:39:35 INF Using conformance image: registry.k8s.io/conformance:v1.31.5
14:39:35 INF …
```
> Add progress indicator to output logs
