.github/workflows/test.yml

I'm not very experienced with github actions but I believe this job will install kind, build and test hydrophone, then run a simple test.
ref: https://github.com/dims/hydrophone/issues/16

Add github actions file to run a simple test against kind

---

go.mod
go.sum

fixes https://github.com/dims/hydrophone/issues/21

update to newer golang

---

.gitignore
go.mod
go.sum
main.go
pkg/client/check.go
pkg/client/client.go
pkg/client/download.go
pkg/client/pod_log.go
pkg/service/init.go

Fix for https://github.com/dims/hydrophone/issues/3

Download files using a second container with emptyDir

---

README.md

@dims let me know if you prefer this for the README.

Updated readme with more accurate output-dir information

---

.github/workflows/periodic_conformance.yml

Add results archiving to help troubleshoot https://github.com/dims/hydrophone/issues/42

Added archiving of conformance results

---

.github/workflows/periodic_conformance.yml
.github/workflows/periodic_e2e.yml
.github/workflows/test.yml

Use the same variable to set the conformance image as the kind version.

Ensure conformance version is the same as kind

---

README.md
pkg/common/args.go
pkg/service/init.go

fix for https://github.com/dims/hydrophone/issues/19

Support for alternate registries for test images (for air-gapped scenarios)

---

pkg/service/init_test.go

Forgot to add license to the top of init_test.go

Added license to init_test.go

---

code-of-conduct.md

Added code of conduct file for k-sig adoption
ref: https://github.com/dims/hydrophone/issues/70

Added code-of-conduct

---

SECURITY.md
SECURITY_CONTACTS

Added security_contacts and security.md file for k-sig adoption
ref: https://github.com/dims/hydrophone/issues/70

Added security contacts

---

docs/air-gapped.md

This PR adds a guide for running hydrophone in an air-gapped environment.

Added air-gapped guide

---

OWNERS
SECURITY_CONTACTS

This PR adds aniruddha2000 to the OWNERS file and SECURITY_CONTACTS

Add aniruddha2000 as an approver and security contact

---

README.md
go.mod
main.go
pkg/client/check.go
pkg/client/client.go
pkg/client/download.go
pkg/client/pod_log.go
pkg/common/args.go
pkg/service/init.go
pkg/service/list_images.go

Updates the repo references to kubernetes-sigs.

Update hydrophone package import paths

---

README.md
go.mod
main.go
pkg/client/check.go
pkg/client/client.go
pkg/client/download.go
pkg/client/pod_log.go
pkg/common/args.go
pkg/service/init.go
pkg/service/list_images.go

Just realized/remembered that we can use `sigs.k8s.io`!

whoops! we can use sigs.k8s.io

---

.gitignore
.goreleaser.yaml

Tweak what we release in our artifacts

Add .goreleaser.yaml

---

Makefile
hack/verify.sh
pkg/client/check.go
pkg/client/client.go
pkg/common/args.go
pkg/common/const.go
pkg/log/logs.go
pkg/service/init.go
pkg/service/list_images.go

Added go verify steps. 
ref: https://github.com/kubernetes-sigs/hydrophone/issues/86
xref: https://github.com/kubernetes/test-infra/pull/31627

Added go verify suite with go fmt go vet and golint

---

hack/dryrun-e2e.sh

transitioning focused test from github actions to prow. ref: https://github.com/kubernetes-sigs/hydrophone/issues/86

added single focus test

---

README.md

fix/readme: minor typo

---

hack/run-e2e.sh

Fixes a very small typo in the new e2e script :)

Very small typo in e2e script

---

hack/run-e2e.sh

Fix https://github.com/kubernetes-sigs/hydrophone/issues/104

Initialize CHECK_DURATION in hack/run-e2e script

---

OWNERS

Adds @rakshitgondwal as a Reviewer in `OWNERS.md` file.

Add rakshitgondwal as reviewer

---

docs/air-gapped.md

corrected mistakes in air-gapped.md

typo and correction in air-gapped.md

---

DEVELOPMENT.md

The documentation did not yet mention the `--cleanup` flag and instead still recommended to manually delete resources.

mention --cleanup in the developer documentation

---

go.mod
hack/verify-gomod.sh

This adds a new verify script that specifically in CI is meant to detect dirty go.mod/go.sum files.

Add go mod tidy checker

---

README.md

Adds a bit more user friendly documentation to the readme.

Updated readme with some basic installation and usage instructions

---

DEVELOPMENT.md
pkg/types/flags.go

Update --test-repo flag description

---

ADOPTERS.md

Added a simple ADOPTERS.md with some placeholders for companies that have been interested in adoption of hydrophone.

Updated with an ADOPTERS.md

---

Dockerfile

@rjsadow @reetasingh I have created container image for Hydrophone and tested on my machine also. Just I had one question that where to store this image in which registry? so one can pull can use it easily

feat: created container image

---

pkg/conformance/client/logs.go

When the log stream ends, Hydrophone considers the tests to be completed and tries to download the results.
In cases where the stream is interrupted but tests are still running (e.g. rolling `kube-apiserver` deployment), this should not happen. Instead, the stream will be started again. This automates `hydrophone --continue` for most cases.
Determining, if tests are still running, is based on ginkgo logs. Specifically, the check looks for a line like this:
```
Ginkgo ran 1 suite in 29m58.847112156s
```
Alternatively, one could base the check on the existence of a `junit_01.xml` file using an `exec` command. But tailing the logs feels more natural to me. Feel free to suggest different tokens that are suitable :)
Addresses #224

Try to recover log streaming upon interrupt

---

pkg/conformance/client/download.go

Recently, I ran into a situation, where SPDY is no longer supported by the proxy routing to a kube-apiserver. This resulted in a failure to download any test results from the conformance pod as the executor was not able to upgrade the connection.
Following [KEP-4006](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/4006-transition-spdy-to-websockets), it would be great if hydrophone could move to `WebSocket` as the preferred protocol 😇 .
Using the `FallbackExecutor` should help with compatibility similar to the [kubectl implementation](https://github.com/kubernetes/kubectl/blob/2e38fc220409bbc92f8270c49612f0f9d8e36c89/pkg/cmd/exec/exec.go#L143-L155).

Use WebSocket executor, when possible

---

go.mod
go.sum

PR filed with output of running hack/bump-k8s.sh on Date: 04/21/2025

Bump Kubernetes on (04/21/2025)

---

docs/understanding-e2e-results.md

E2e results reporting guide for better understanding
resolves #261

E2E results reporting guide

---

README.md
docs/README.md
docs/quickstart.md

Add Quickstart Guide (#258)

---

docs/flags-cli-ref.md

Add docs for flags and cli

---

Makefile

PR to add functionality requested in #273

Split make test into make test-unit and make test-race
